avatar: /img/avatar.png

links:
  Github: https://github.com/Anillc
  About: /about
  Links: /links

ga: 'G-T5TJQM3LBN'

footer: '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">知识共享署名-相同方式共享 4.0 国际许可协议</a>'
