avatar: 'https://gravatar.loli.net/avatar/5df946d48b36e6f8061cdfe7ebcdf75c?s=512'

links:
  Github: https://github.com/Anillc
  Kanocat: https://kano.cat
  Networking: https://ani.llc/networking
  About: https://ani.llc
  More: /more

ga: 'G-T5TJQM3LBN'

footer: '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">知识共享署名-相同方式共享 4.0 国际许可协议</a>'
